function adot = adotfunc(dq4,q4)
%ADOTFUNC
%    ADOT = ADOTFUNC(DQ4,Q4)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    05-Sep-2019 14:17:35

t2 = sin(q4);
t3 = cos(q4);
t4 = dq4.*t3;
adot = reshape([-dq4.*t2,-dq4.*t2,t4,t4,t4,dq4.*t2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,6]);
