function a = afunc(d,q4,r)
%AFUNC
%    A = AFUNC(D,Q4,R)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    05-Sep-2019 14:17:35

t2 = cos(q4);
t3 = sin(q4);
a = reshape([t2,t2,t3,t3,t3,-t2,0.0,0.0,0.0,d.*(-1.0./2.0),d.*(1.0./2.0),0.0,-r,0.0,0.0,0.0,-r,0.0],[3,6]);
