function CE = CEfunc(d,dq1,dq2,dq4,dq5,dq6,q4,r)
%CEFUNC
%    CE = CEFUNC(D,DQ1,DQ2,DQ4,DQ5,DQ6,Q4,R)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    05-Sep-2019 14:17:35

t3 = d.*dq4.*(1.0./2.0);
t4 = cos(q4);
t5 = dq1.*t4;
t6 = sin(q4);
t7 = dq2.*t6;
t2 = t3-t5-t7+dq5.*r;
t8 = t3+t5+t7-dq6.*r;
t9 = dq2.*t4-dq1.*t6;
CE = t2.^2+t8.^2+t9.^2;
