function M = Mfunc(I1,I2,I3,J,K,Mb,Mw,d,l,q3,q4,r)
%MFUNC
%    M = MFUNC(I1,I2,I3,J,K,MB,MW,D,L,Q3,Q4,R)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    05-Sep-2019 14:17:34

t2 = cos(q4);
t3 = r.^2;
t4 = 1.0./r.^2;
t5 = J.*2.0;
t6 = Mb.*t3;
t7 = Mw.*t3.*2.0;
t8 = t5+t6+t7;
t9 = sin(q3);
t10 = q4.*2.0;
t11 = sin(t10);
t12 = t4.*t8.*t11.*(1.0./2.0);
t13 = sin(q4);
t14 = t9.^2;
t15 = Mb.*l.*t2.*t14;
t16 = Mb.*l.*t13.*t14;
t17 = d.^2;
t18 = l.^2;
M = reshape([t2.^2.*t4.*t8,t12,0.0,t15,0.0,0.0,t12,t4.*t8.*t13.^2,0.0,t16,0.0,0.0,0.0,0.0,I2+Mb.*t18,0.0,0.0,0.0,t15,t16,0.0,t4.*(I3.*t3.*2.0+J.*t17+K.*t3.*4.0+I1.*t3.*t14.*2.0-I3.*t3.*t14.*2.0+Mw.*t3.*t17+Mb.*t3.*t14.*t18.*2.0).*(1.0./2.0),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,6]);
